### PR TITLE
fixing config key error

### PR DESCRIPTION
**Pull request by choldgraf**
This fixes a bug that @najuzilu reported

### CODE REVIEW

**Comment by najuzilu** [comment]
I figured out what is happening. The error occurs when I do not add `path_to_book : ""` under `repository`. Is this by design?

**Comment by choldgraf** [comment]
It should be fixed by this PR... Does it still not work if you don't provide that config value at all?

**Comment by najuzilu** [comment]
The example below throws this ValueError: `You must provide the key: repository_url to add Binder buttons.`
```
repository:
  url                       : ""
  path_to_book              : ""
```

This example throws the error I mentioned previously: `AttributeError: 'NoneType' object has no attribute 'strip'`
```
repository:
  url                       : https://github.com/ExecutableBookProject/quantecon-example/tree/master/book/docs
```

Whereas this example does not throw any errors:
```
repository:
  url                       : https://github.com/ExecutableBookProject/quantecon-example/tree/master/book/docs
  path_to_book              : ""
```

So, it looks like we're required to have both but we can't have one without the other. I was wondering if that's on purpose.

**Comment by choldgraf** [comment]
ok give it another shot, I think it's fixed in #27

**Comment by najuzilu** [comment]
It's working great now! Thanks @choldgraf

**Pull request merged**
