### PR TITLE
removing button backgrounds and text

### PR DESCRIPTION
**Pull request by choldgraf**
This prototypes removing button backgrounds and text (text now shows on hover). What do people think about it? cc @AakashGfude @jstac @najuzilu @chrisjsewell

### CODE REVIEW

**Comment by choldgraf** [comment]
I think that it looks cleaner - if folks don't think that removing the text is a problem, then I'd be +1 on merging this and iterating from there...

**Comment by AakashGfude** [comment]
+1 on this. It looks neat. I also think that those tooltip texts `download this page` and `launch interactive content` might be a bit obtrusive for the dropdown and we can do without it?

**Comment by jstac** [comment]
Yes, it looks much cleaner.  Nice one.  Without text there's less distraction from the heading.  

@chrisjsewell also suggested right aligned and that sounds good too --- but either way I agree on making this change and then iterating.

**Comment by choldgraf** [comment]
let's merge this one and then we can iterate on right-aligned in another issue. I want to leave the tooltips for now, partially because they're a bit more accessibility-friendly. Thanks for the feedback!

**Pull request merged**
