### PR TITLE
figures and captions

### PR DESCRIPTION
**Pull request by choldgraf**
Updates CSS for figure captions, also adds rules for sidebar captions:

https://147-244496643-gh.circle-artifacts.com/0/html/reference/limits.html#common-publishing-items

### CODE REVIEW

**Comment by choldgraf** [comment]
@najuzilu I've sent an invite to add you as a maintainer on this repository, in case you'd like to give this a merge when you're happy with it. Otherwise I'll merge a bit later unless you have comments

**Comment by najuzilu** [comment]
Nicely done! I think aligning figures should be kept at a theme level. Should I remove the PR about aligning figures from `MyST-NB` then?

**Comment by najuzilu** [comment]
Also, is there a `:target:` equivalent in MyST-NB? Just wandering because I'm compiling a list of all parameters supported for figures.

**Comment by choldgraf** [comment]
Hmmm, I am not sure what `target` is :-)  so...maybe?

**Comment by najuzilu** [comment]
Actually the target is set by default. I didn't realize that figures were "clickable".

**Pull request merged**
