### PR TITLE
Use pypi packages in requirements

### PR DESCRIPTION
**Pull request by chrisjsewell**

### CODE REVIEW

**Comment by choldgraf** [comment]
Do we think that things are settling down on the myst-nb/myst-parser/etc side? I have been keeping these pinned to "master" for the time being because those tools were evolving so rapidly, and it saved time bumping version numbers each time.

(and, for example, there are a few things in here that are in the pydata theme master but not yet released)

**Comment by chrisjsewell** [comment]
With ExecutableBookProject/MyST-NB#116, that's the last of the big planned changes/additions (for now!)

**Comment by choldgraf** [comment]
I'm going to merge this once pydata-sphinx-theme gets another version bump, because we're depending on some things that are in master. Once that happens I'll make a proper release for this theme as well

**Comment by choldgraf** [comment]
I just cut [a release in pydata-sphinx-theme](https://github.com/pandas-dev/pydata-sphinx-theme/releases/tag/v0.2.0), so updated this PR and we'll see how it looks. If all is well then I'll merge!

**Comment by choldgraf** [comment]
hmmm - [we have tests failing](https://github.com/ExecutableBookProject/sphinx-book-theme/pull/35/checks?check_run_id=606670258#step:5:129). Could this be because we're depending on something in a master branch that isn't released yet?

**Comment by choldgraf** [comment]
OK I do think this is because we haven't released MyST-NB in a little while - I can cut a new release (see https://github.com/ExecutableBookProject/MyST-NB/issues/161) once I confirm the release instructions

**Comment by choldgraf** [comment]
wooo! packages are pinned! let's cut a release :-)

**Pull request merged**
